config/routes.rb
Rails.application.routes.draw do
  
  resources :lists
  
  root 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @list=List.all
    end
    
    def new
        @list=List.new
    end
    
    def show
        @list=List.find(params[:id])
    end
    
    def create
        @list=List.new(list_params)
        if @list.save
            redirect_to lists_path
        else
            render 'new'
        end
    end
    
    def edit
        @list=List.find(params[:id])
    end
    
    def update
        @list=List.find(params[:id])
        if @list.update(list_params)
            redirect_to lists_path
        else
            render 'edit'
        end
    end
    
    def destroy
        List.find(params[:id]).destroy
        redirect_to lists_path
    end
    
    private
        def list_params
            params.require(:list).permit(:name,:user,:expire_date)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/edit.html.erb
<h1>作業更新</h1>

<%= form_for @list do |f| %>
<p>
    <%= f.label :name , "項目名" %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :user ,"担当者" %>
    <%= f.text_field :user %>
</p> 

<p>
    <%= f.label :expire_date ,"期限" %>
    <%= f.date_field :expire_date %>
</p> 

<p>
    <%= f.submit "更新",data: {disable_with: "更新中..."} %> 
    <%= link_to "キャンセル",lists_path %>
</p>
<% end %>

app/views/lists/index.html.erb
<h1>ToDo List</h1>

<p><%= link_to "作業登録",new_list_path %></p>
<p style="margin-bottom: 2em;"> 
    <table border=3 cellpadding=5 width=500>
        <tr>
            <th>項目名</th>
            <th>担当者</th>
            <th>期限</th>
            <th>操作</th>
        </tr>

        <% @list.each do |list| %>
        <tr>
    
            <td><%= list.name %></td>
            <td><%= list.user %></td>
            <td align=center><%= list.expire_date %></td>
            <td align=center>
                <%= link_to "更新",edit_list_path(list) %>
                <%= link_to "削除",list_path(list),method: :delete %>
            </td>
        </tr>
        <% end %>
    </table> 
</p>
    

app/views/lists/new.html.erb
<h1>作業登録</h1>

<%= form_for @list do |f| %>
<p>
    <%= f.label :name , "項目名" %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :user ,"担当者" %>
    <%= f.text_field :user %>
</p> 

<p>
    <%= f.label :expire_date ,"期限" %>
    <%= f.date_field :expire_date %>
</p> 


<p>
    <%= f.submit "登録",data: {disable_with: "登録中..."} %> 
    <%= link_to "キャンセル",lists_path %>
</p>
<% end %>